import { Routes, Route } from 'react-router-dom';
import Nosotros from './componentes/Nosotros';
import Users from './componentes/Users';
import Login from './componentes/Login';
import Registro from './componentes/Registro';
import Contacto from './componentes/Contacto';
import List from './componentes/List';
import { UserProvider } from './UserContext';
import './App.css';
import NotFound from './componentes/NotFound';
import category from './componentes/category';
import description from './componentes/description';
import detail from './componentes/detail';
import discount from './componentes/discount';
import Footer from './componentes/Footer';
import Header from './componentes/Header';
import product_image from '.componentes/product_image';
import product from './componentes/product';
export default App;